GoogleCloudPlatform/synthetics-sdk-nodejs

packages/synthetics-sdk-broken-links/src/broken_links.ts, packages/synthetics-sdk-broken-links/src/handlers.ts, packages/synthetics-sdk-broken-links/src/link_utils.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts, packages/synthetics-sdk-broken-links/test/unit/link_utils.spec.ts
For ease of use for customers rather than exporting the generated typescript type BrokenLinksResultV1_BrokenLinkCheckerOptions from the proto I am redeclaring the interface as BrokenLinkCheckerOptions, which will be exported to public.
One of the primary reasons for this is that I want to make all fields except origin_url optional, however I cannot use the "optional" keyword as freely in the proto for large Google style reasons. 
The changes are relatively simple except that figuring out how to convert translate per_link_options from one type to the other is tricky.
=> update input interfaces

package-lock.json, packages/synthetics-sdk-api/proto/synthetic_response.proto, packages/synthetics-sdk-api/src/generated/proto/synthetic_response.ts, packages/synthetics-sdk-broken-links/package.json, packages/synthetics-sdk-broken-links/src/broken_links.ts, packages/synthetics-sdk-broken-links/src/link_utils.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts
this PR creates a function `checkLink()` which acts as a wrapper for error handling and `SyntheticLinkResult` creation (api parseable object for individual link navigation).
Note that the real action/link-navigation happens in `navigate(..)`. Some of the tests used to be `navigate` tests that were expanded to be `checkLink` tests. My logic here was that all the `navigate` functionality is still being tested and since checkLink is basically just a wrapper on top it does not make sense to have separate unit tests. Rather larger tests (similar to how we test logs).
ps. fixing link_start_time & link_end_time to be camelcase
=> check link

.github/release-please.yml, release-please-config.json
The initial configuration o the release please bot, yielded a PR that released an initial version of the root repository. Since we are monorepo, we need to release the sub packages only. Additionally! The release-please-config.json file had invalid content (an extra comma). 
See incorrect PR: https://github.com/GoogleCloudPlatform/synthetics-sdk-nodejs/pull/33
This change _should_ make release please to use manifest file, which _should_ make monorepo work. Let's see!
=> chore: Previous release please yml didnt use manifest

packages/synthetics-sdk-api/test/unit/runtime_metadata_extractor.spec.ts
This changes the package version check to presence of non-empty string, from exact equality. This makes it so that newly tagged versions of SDK's do not break this test.
=> chore: Change test for request metadata 

.github/workflows/publish.yml
Background: When you postfix a command in npm with `--workspaces`, it runs that command in each package, and if it fails at any step, the whold step stops. So if you're trying to run npm run test --workspaces, and you have 5 packages, if the tests fail at package 3, tests in 4 and 5 wont run.
This is problematic with this workflow in that we're only publishing one package at a time. This means that if when running through each package running `npm publish` fails, then it wont try the next one. The failure that we're particularly concerned with is when there is no update to the package, and you get a 403 back. 
This change runs npm publish in each package individually, as separated by `||`, so that it runs until one package has been published.
=> chore: Separates npm publish commands in publish workflow

.husky/commit-msg, commitlint.config.js, package-lock.json, package.json
With the recent change to add automated tagging via release-please, we need all commits to be in the form of a conventional commit from here on out. This change forces commits to be in a conventional format.
Blocking usage example:
```bash
$ git commit -m "blob"
⧗   input: blob
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```
dependency documentation: https://github.com/conventional-changelog/commitlint
=> chore: adds pre-commit hook, requires conventional commit

package-lock.json, packages/synthetics-sdk-broken-links/src/broken_links.ts, packages/synthetics-sdk-broken-links/src/link_utils.ts, packages/synthetics-sdk-broken-links/test/unit/link_utils.spec.ts
This PR write a function that makes sure all the inputOptions are valid. 
Overall validation: 
- extra fields are filtered out from the object
- all inputOptions are valid if they are undefinied/omitted, EXCEPT origin_url
Per field validation:
- origin_url: Must be present, must start with 'http'
- link_limit: must be a number greater than 0
- query_selector_all: must be a non-empty string
- get_attributes: must be an array of strings
- link_order: must be FIRST_N or RANDOM from LinkOrder enum `OR` can be a string of either of those (for js compatibility)
- link_timeout_millis: must be a number greater than 0
- max_retries: must be a number greater than -1
- max_redirects: must be a number greater than -1
- wait_for_selector: must be a non-empty string
- per_link_options:
key -- url: must …
=> options_validity

packages/synthetics-sdk-broken-links/package.json, packages/synthetics-sdk-broken-links/src/broken_links.ts, packages/synthetics-sdk-broken-links/src/handlers.ts, packages/synthetics-sdk-broken-links/src/navigation_func.ts, packages/synthetics-sdk-broken-links/test/example_html_files/integration_server.js, packages/synthetics-sdk-broken-links/test/integration/integration.spec.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts
The integration tests test the following scenario:
- Handles error when trying to visit page that does not exist
- Visits and checks empty page with no links
- Exits early when options cannot be parsed
- Completes full failing execution
- Completes full passing execution
Other changes
- instantiate metdata in `broken_links.ts`
- fix name in package.json
=> integration tests

packages/synthetics-sdk-broken-links/src/navigation_func.ts, packages/synthetics-sdk-broken-links/src/options_func.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts, packages/synthetics-sdk-broken-links/test/unit/navigation_func.spec.ts, packages/synthetics-sdk-broken-links/test/unit/options_func.spec.ts
Limits the number of redirects on a per to max_redirects
Also changes minimum max_timeout_millis to be 10ms since when the timeout is less than that sometimes it causes the page.on('request') call to hang.
=> implement logic to limit redirects to options.max_redirects

packages/synthetics-sdk-broken-links/src/navigation_func.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts, packages/synthetics-sdk-broken-links/test/unit/navigation_func.spec.ts
This change does 3 things:
1. Prior to any request interception or handling we need to check if it has already been handled by an unknown third-party per puppeteer documention. (change in code:  `!request.isInterceptResolutionHandled()` before any call to `request.respond()` or `request.continue()`). 
Puppeteer documentation: 
```It is therefore important to always check the resolution status using [request.isInterceptResolutionHandled](https://github.com/puppeteer/puppeteer/blob/59578d9cd5709bebe3117f8e060ad7cab220b3df/docs/api.md#httprequestisinterceptresolutionhandled) before calling abort/continue/respond.```
2.  In order to stop the navigationRequest when the number of redirects gets too large we need to keep track of the total number of redirects. I was previously initializing …
=> fix redirect function

package-lock.json, packages/synthetics-sdk-api/package.json
The latest *patch* version of @opentelemetry/auto-instrumentation-node introduces a breaking change such that for newly created synthetics (no package-lock to point to old versions of @opentelemetry/auto-instrumentation-node), no traces are being written. 
This change locks all production dependencies to exact versions of dependencies, rather than the latest minor version. This is a defensive measure against developers in the OS ecosystem causing breaking changes at either the minor or patch levels.
See: generic-synthetic-nodejs w/ current version 0.3.0 of @google-cloud/synthetics-sdk-api.
See: generic-synthetic-nodejs w/ packed version of this change of @google-cloud/synthetics-sdk-api.
=> fix: Fixes broken patch dependencies

package-lock.json
Releasing synthetics-sdk-api: v0.4.0 failed ([Link to build failure](https://github.com/GoogleCloudPlatform/synthetics-sdk-nodejs/actions/runs/6512404501)), blocking progress on updating samples.
=> fix: updates package-lock to include new node-mocks-http dependency

samples/generic-synthetic-nodejs/index.js, samples/generic-synthetic-nodejs/package.json, samples/generic-synthetic-typescript/package.json, samples/generic-synthetic-typescript/src/index.ts
Synthetics sdk v0.4.1 includes the ability to access execution id from within the user's code snippet. This change updates the samples to reflect the new feature.
Tested via cloud function deployment: 
- node js: 
- ts:
=> chore: updates nodejs and ts samples to incorporate execution id

packages/synthetics-sdk-broken-links/src/link_utils.ts, packages/synthetics-sdk-broken-links/test/unit/link_utils.spec.ts
if SDK reports latency of 0 secs causes a bug in how we report metrics. This change makes sure that the minimum latency is 1 millisecond
=> fix: zero latency fix 

package-lock.json, packages/synthetics-sdk-api/src/generated/proto/synthetic_response.ts, packages/synthetics-sdk-broken-links/package.json, packages/synthetics-sdk-broken-links/src/broken_links.ts, packages/synthetics-sdk-broken-links/src/options_func.ts, packages/synthetics-sdk-broken-links/test/integration/integration.spec.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts, packages/synthetics-sdk-broken-links/test/unit/options_func.spec.ts
Allows users to specify how long the synthetic is going to run. We then remove 7 seconds from this time and return all the links we've been able to check in that time.
Support for this already existed but it was hard coded to 50 seconds. This change is exposing this capability to the user.
=> feat: Add support through package to support users providing a `total_synthetic_timeout_millis` option

package-lock.json, packages/synthetics-sdk-api/package.json, packages/synthetics-sdk-api/src/cloud_region_resolver.ts, packages/synthetics-sdk-api/src/index.ts, packages/synthetics-sdk-api/test/unit/cloud_region_resolver.spec.ts
For better long-term integration and reduced dependencies, I'm implementing this functionality within the synthetics-sdk-api.  Placing it directly in the broken-links package would necessitate importing it into future SDKs, creating additional dependencies. This approach ensures reusability across future synthetic SDKs without that overhead.
=> get-cloud-region

packages/synthetics-sdk-broken-links/src/storage_func.ts, packages/synthetics-sdk-broken-links/test/unit/storage_func.spec.ts
This change mainly introduces the `uploadScreenshotToGCS()` function and its helper `getFolderNameFromStorageLocation()` both of these functions are tested in the corresponding spec.ts file.
uploadScreenshotToGCS will be called within the checkLink function in navigation_func. This function will only be called if the user's screenshotCondition and link status align.
I've additionally added an assertion in an earlier test for code coverage reasons.
=> upload screenshot to GCS Bucket

packages/synthetics-sdk-broken-links/src/broken_links.ts, packages/synthetics-sdk-broken-links/src/handlers.ts, packages/synthetics-sdk-broken-links/src/index.ts, packages/synthetics-sdk-broken-links/src/link_utils.ts, packages/synthetics-sdk-broken-links/src/navigation_func.ts, packages/synthetics-sdk-broken-links/src/options_func.ts, packages/synthetics-sdk-broken-links/src/storage_func.ts, packages/synthetics-sdk-broken-links/test/example_html_files/integration_server.js, packages/synthetics-sdk-broken-links/test/integration/integration.spec.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts, packages/synthetics-sdk-broken-links/test/unit/link_utils.spec.ts, packages/synthetics-sdk-broken-links/test/unit/navigation_func.spec.ts, packages/synthetics-sdk-broken-links/test/unit/options_func.spec.ts, packages/synthetics-sdk-broken-links/test/unit/storage_func.spec.ts
The integration.spec.ts and integration_server.js are "integration" tests in that they test the code within a mock cloud function environment. This is helpful to make sure that runtime_metadata is present and that http_headers are sent correctly. The current testing can almost entirely be done in the broken_links.spec.ts file, which is where I am migrating the code.
Because in the integration_server the broken_links package is imported as `const SyntheticsSdkBrokenLinks = require('synthetics-sdk-broken-links');` it makes code impossible to mock. So in anticipation of my integration with Cloud Storage, where I will need to mock lots of functionality I am moving these tests to broken_links.spec.ts
The cloud Storage integration will be integration tested through CEP workflows.
Also I've …
=> Refactor Integration Tests & Organize Imports

packages/synthetics-sdk-broken-links/src/link_utils.ts, packages/synthetics-sdk-broken-links/src/storage_func.ts, packages/synthetics-sdk-broken-links/test/integration/integration.spec.ts, packages/synthetics-sdk-broken-links/test/unit/broken_links.spec.ts, packages/synthetics-sdk-broken-links/test/unit/link_utils.spec.ts
Sanitize function is based on: https://cloud.google.com/storage/docs/objects#naming
=> sanitize strings

package-lock.json, packages/synthetics-sdk-api/package.json, packages/synthetics-sdk-api/proto/synthetic_response.proto, packages/synthetics-sdk-api/src/cloud_region_resolver.ts, packages/synthetics-sdk-api/src/generated/proto/synthetic_response.ts, packages/synthetics-sdk-api/src/index.ts, packages/synthetics-sdk-api/test/unit/cloud_region_resolver.spec.ts
This is the official merge into `main` for all changes in the synthetics-sdk-api relating to the addition of screenshots. (All changes merged into this branch have been previously reviewed).
=> feat: update proto to support broken link screenshot support & add getExecutionRegion() functionality
